### ISSUE TITLE
iOS build error!

### ISSUE THREAD

**Issue by mrstluo** [arcticfox1919/flutter-scankit#1]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.6 19G2021 darwin-x64,
    locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

/Users/test1/klapp/aaa/flutter_app1/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/test1/klapp/aaa/flutter_app1/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork' for architecture arm64

**Comment by arcticfox1919** [comment]
@mrstluo 
Perhaps you should heed the prompt message that reports the error and disable the bitcode. The reason for this error is probably because the HUAWEI ScanKit SDK does not provide bitcode support.

You can see this setting in the "Build Settings" -> "Enable Bitcode" option. Just set it to NO

**Comment by git-boya** [comment]
i try set 'Enable Bitcode" to NO, bug the problem has not been solved

It can be solved by the following method:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    #start
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
   #end
  end
end
```
