### ISSUE TITLE
解除绑定的问题

### ISSUE THREAD

**Issue by guicai666** [arcticfox1919/flutter-scankit#10]
我在首页底部的Tab键个扫码的功能 商品添加也有一个扫码功能  第一次当我通过扫码跳转商品添加  第二次就继续通过首页进入商品添加界面时 首页的扫码代码就不走了 

https://user-images.githubusercontent.com/31101499/133034119-71c8cc7e-7039-4ce5-91ed-f883c3b77682.mp4

**Comment by guicai666** [comment]
能方便的话加个微信

**Comment by arcticfox1919** [comment]
请添加相关代码，或者编写Demo验证问题，确保问题不是因为使用错误导致
