### ISSUE TITLE
从相册选取，所选图片没有条码时，没有任何提示，仍停留在扫码界面

### ISSUE THREAD

**Issue by NRMrYang** [arcticfox1919/flutter-scankit#12]
安卓端的Scankit是有提示的（如下图所示），作者是否可以在Flutter也增加一个？辛苦！

![image](https://user-images.githubusercontent.com/29404224/133737555-e2927b1f-97ec-451d-8cca-4f12b9836459.png)

**Comment by arcticfox1919** [comment]
@NRMrYang 最新版本scankit并无此弹窗，且该类需求属于应用层业务逻辑，并不属于SDK的范畴，SDK仅提供识别二维码的服务。请自行监听识码回调，根据自身业务逻辑，自行创建弹框

**Comment by NRMrYang** [comment]
问题是没有码的时候，仍然停留在扫码界面，addResultListen也没有返回值啊。。。如果有我肯定就自己加了

**Comment by NRMrYang** [comment]
我没有用自定义扫码界面，默认扫码界面是否就不能监听图片无码情况的回调了？

**Comment by arcticfox1919** [comment]
@NRMrYang 
是的，默认扫码界面是SDK scankit提供的快捷使用方式，Flutter插件仅包装它暴露的两个接口。若监听无返回，表明底层并未提供图片未识别二维码状态下的反馈。scankit 并不开源，其行为会随着版本不同而有所不同，具体不甚清晰，官方文档亦未详细描述版本变化。若要处理该需求，可以考虑自定义UI

**Comment by NRMrYang** [comment]
好的，十分感谢，我尝试一下自定义扫码界面
