### ISSUE TITLE
Undefined symbols for architecture armv7 

### ISSUE THREAD

**Issue by git-boya** [arcticfox1919/flutter-scankit#13]
ios debug可以用,打包ipa报错
```
ld: warning: ignoring file /Users/ieducc/develop/cloud/flutter_cloud/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork, missing required architecture armv7 in file
    /Users/ieducc/develop/cloud/flutter_cloud/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork (2 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_HmsBitMap", referenced from:
          objc-class-ref in FLScanKitView.o
          objc-class-ref in FlutterScankitPlugin.o
      "_OBJC_CLASS_$_HmsDefaultScanViewController", referenced from:
          objc-class-ref in FlutterScankitPlugin.o
      "_OBJC_CLASS_$_HmsCustomScanViewController", referenced from:
          objc-class-ref in FLScanKitView.o
      "_OBJC_CLASS_$_HmsScanOptions", referenced from:
          objc-class-ref in FLScanKitView.o
          objc-class-ref in FlutterScankitPlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
```
在xcode12要怎样设置才能移除armv7支持

**Comment by arcticfox1919** [comment]
@git-boya 
华为 scankit 是不开源的，以二进制形式分发。目前scankit framework中并不包含armv7架构的二进制，因此Flutter打包时不要添加armv7架构。

选择 Build Setting， 搜索 VALID_ARCHS，然后去掉 armv7 选项。注意：debug 和 release 都删掉

**Comment by git-boya** [comment]
> @git-boya
> 华为 scankit 是不开源的，以二进制形式分发。目前scankit framework中并不包含armv7架构的二进制，因此Flutter打包时不要添加armv7架构。
> 
> 选择 Build Setting， 搜索 VALID_ARCHS，然后去掉 armv7 选项。注意：debug 和 release 都删掉

xcode12 没有VALID_ARCHS了
网上查是用Excluded Architectures设置,我这么设置还是编译不过去.ios不太会弄啊
![image](https://user-images.githubusercontent.com/17589102/133754436-c58d3135-39e0-4318-a8fa-07aa7c5f4778.png)
![image](https://user-images.githubusercontent.com/17589102/133754546-beddf8ef-6b39-4291-ae75-bf142017adcc.png)

**Comment by arcticfox1919** [comment]
![](https://gitee.com/arcticfox1919/ImageHosting/raw/master/img/2021-09-17.png)

选择 Build Setting， 搜索arm

**Comment by git-boya** [comment]
感谢作者 问题解决了

**Comment by guicai666** [comment]
谢谢作者 解决了

**Comment by zkooo** [comment]
同楼上 报错

**Comment by weigoudan** [comment]
您好，我还是想问问怎么加armv7，我的project和targets都加了怎么打包还是报错？？（插件用的是1.2.3版本）

![企业微信截图_719e7e58-a1c6-4ce7-b427-20b82bcae01f](https://user-images.githubusercontent.com/26270819/162661439-dd6bf375-a586-402e-a87f-06813b3eb9c7.png)
![企业微信截图_ec029891-733f-493e-9152-d697ce3879d6](https://user-images.githubusercontent.com/26270819/162661446-df280427-6884-433b-8f7f-4072cb41b2b3.png)

**Comment by arcticfox1919** [comment]
@weigoudan 
我上面已经说了，华为这个库不支持armv7

**Comment by git-boya** [comment]
> 
改Architectures那项试试

**Comment by weigoudan** [comment]
> 改Architectures那项试试
谢了，就是这个，后面重新把工程里的pod有关的全删了再重新pod install才可以，有毒

**Comment by xiejibiao** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/30366768/165718294-88b1dfd4-56ab-40ce-a797-7c2f7c373bae.png">
我已经是按照图上的配置的，但是还是有异常呀，有人能救救我吗？

**Comment by arcticfox1919** [comment]
@xiejibiao 1. 只能用真机 2. 删除缓存,重新pod install 试一试

**Comment by EmreSURK** [comment]
hi, did these solutions work for you?

**Comment by MakenChan** [comment]
> 

yes

**Comment by peakandyuri** [comment]
如果不能解决，可以考虑使用google mlkit库来替代，pub上有很多相关的插件
