### ISSUE TITLE
iPad 横屏模式下取景方向有问题

### ISSUE THREAD

**Issue by hellohejinyu** [arcticfox1919/flutter-scankit#16]
Hello～非常感谢写了这个 Flutter 插件，因为我对原生开发不熟悉。然后这个插件在横屏模式下扫码取景方向有问题，不知道作者是否有空修复一下这个问题呢？

![IMG_ACF637429AC4-1](https://user-images.githubusercontent.com/8766034/134923897-02ff6a39-7ec5-49cc-8d40-ef059b775749.jpeg)
![IMG_ACF637429AC4-2](https://user-images.githubusercontent.com/8766034/134923911-934c2033-5da0-45a2-b5f9-b6b6805042cf.jpeg)

**Comment by ophioglossum** [comment]
我也遇到这个问题了，扫码特别别扭

**Comment by laoduan395** [comment]
所以这个横屏模式下  摄像头取景方向的问题有修复吗

**Comment by hellohejinyu** [comment]
> 所以这个横屏模式下 摄像头取景方向的问题有修复吗

不清楚，后面项目中我改为使用 `google_mlkit_barcode_scanning` 来实现扫码功能了。
