### ISSUE TITLE
扫码完毕之后抛出异常

### ISSUE THREAD

**Issue by fire1974** [arcticfox1919/flutter-scankit#21]
The following MissingPluginException was thrown while de-activating platform stream on channel xyz.bczl.flutter_scankit/event:
MissingPluginException(No implementation found for method cancel on channel xyz.bczl.flutter_scankit/event)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:498:9)
<asynchronous suspension>

小米11，flutter2.5.3

**Comment by arcticfox1919** [comment]
v1.2.1修复
