### ISSUE TITLE
安卓下如果页面弹出键盘时，跳转到customized_view会黑屏

### ISSUE THREAD

**Issue by swieer** [arcticfox1919/flutter-scankit#22]
安卓下真机，如果页面弹出键盘时，比如textField正在输入，如果不收起键盘，直接点击跳转到customized_view会黑屏。
可以在example上增加一个textField， autoFocus：true，可以复现

**Comment by arcticfox1919** [comment]
这不是库的功能性问题！如果自定义扫码UI，应用开放者应该自行控制避免冲突，否则请使用高度封装的一键扫码功能

**Comment by arcticfox1919** [comment]
@swieer 
这不是库的功能性问题！如果自定义扫码UI，应用开发者应该自行控制避免冲突，否则请使用高度封装的一键扫码功能
