### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by guicai666** [arcticfox1919/flutter-scankit#24]
`Xcode's output:
↳
    ld: warning: ignoring file /Users/wt01/Desktop/app/mini-cashier-app/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork, missing required architecture armv7 in
    file /Users/wt01/Desktop/app/mini-cashier-app/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork (2 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_HmsBitMap", referenced from:
          objc-class-ref in FLScanKitView.o
          objc-class-ref in FlutterScankitPlugin.o
      "_OBJC_CLASS_$_HmsDefaultScanViewController", referenced from:
          objc-class-ref in FlutterScankitPlugin.o
      "_OBJC_CLASS_$_HmsCustomScanViewController", referenced from:
          objc-class-ref in FLScanKitView.o
      "_OBJC_CLASS_$_HmsScanOptions", referenced from:
          objc-class-ref in FLScanKitView.o
          objc-class-ref in FlutterScankitPlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
`
请教大佬帮帮忙看看   急急急！！！

**Comment by arcticfox1919** [comment]
与[issues13](https://github.com/arcticfox1919/flutter-scankit/issues/13)重复

**Comment by guicai666** [comment]
谢谢作者 解决了问题
