### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by nanguaSky** [arcticfox1919/flutter-scankit#28]
scankit：v.1.2.3
设备：小米10pro、华为均会出现

我在扫码界面有个手动输入编号的按钮可以跳转到另一个页面输入，输入完成后pop到扫码界面然后继续pop到上一级页面，这过程当中有挺大的几率会出现这个问题，一下是我的代码
`class ScanCodePage extends BaseStatefulWidget {

  bool scanBicycle;

  ScanCodePage({this.scanBicycle = false});

  @override
  State<StatefulWidget> createState() => _ScanCodeState();
}

const boxSize = 200.0;

class _ScanCodeState extends BaseState<ScanCodePage, ScanCodeViewModel> with WidgetsBindingObserver {

  final screenWidth = window.physicalSize.width;
  final screenHeight = window.physicalSize.height;

  late ScanKitController _controller;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addObserver(this);
  }

  @override
  Widget build(BuildContext context) {
    var stateHeight = ScreenUtil.getStatusBarHigh();
    var pixelSize = boxSize * window.devicePixelRatio;
    var left = screenWidth/2 - pixelSize/2;
    var top = screenHeight/2 - pixelSize/2;
    var right = screenWidth/2 + pixelSize/2;
    var bottom = screenHeight/2 + pixelSize/2;
    var rect = Rect.fromLTRB(left, top, right, bottom);

    return Scaffold(
      body: Stack(
        children: [
          ScanKitWidget(
            format: const [ScanTypes.QRCODE],
            callback: (controller) {
              _controller = controller;
              controller.onResult.listen((result) {
                debugPrint("scanning result:$result");
                Navigator.of(context).pop(result);
              });
            },
            continuouslyScan: false,
            boundingBox: rect
          ),

          ///文本提示
          Offstage(
            offstage: !widget.scanBicycle,
            child: Align(
              alignment: Alignment.center,
              child: Padding(
                padding: EdgeInsets.only(bottom: 400),
                child: Text(MString.scan_hint, style: TextStyle(color: Colors.white, fontSize: 16),),
              ),
            ),
          ),

          ///扫描边框
          Align(
            alignment: Alignment.center,
            child: Container(
              width: boxSize,
              height: boxSize,
              child: Image.asset(ImageAssets.imagesIconScanBorder, width: boxSize, height: boxSize),
            ),
          ),

          ///返回按钮
          Positioned(
            top: stateHeight,
            left: 8,
            child: IconButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              icon: Image.asset(ImageAssets.imagesIconScanBack)
            ),
          ),

          ///相册选择
          Positioned(
            top: stateHeight,
            right: 8,
            child: Offstage(
              offstage: widget.scanBicycle,
              child: IconButton(
                  onPressed: () {
                    _controller.pickPhoto();
                  },
                  icon: Image.asset(ImageAssets.imagesIconScanPhoto)
              ),
            ),
          ),

          ///底部2个开关按钮
          Offstage(
            offstage: !widget.scanBicycle,
            child: Container(
              margin: EdgeInsets.only(bottom: 54.5, left: 30, right: 30),
              alignment: Alignment.bottomCenter,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [

                  ///手动输入
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      IconButton(
                        onPressed: () { _jumpInputBikeNum(); },
                        icon: Image.asset(ImageAssets.imagesIconScanInputNum),
                        iconSize: 50,
                      ),
                      Text(MString.scan_input_num, style: TextStyle(color: Colors.white, fontSize: 14),)
                    ],
                  ),

                  ///打开手电筒
                  Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      IconButton(
                        onPressed: () {
                          _controller.switchLight();
                        },
                        icon: Image.asset(ImageAssets.imagesIconScanLight),
                        iconSize: 50,
                      ),
                      Text(MString.scan_open_light, style: TextStyle(color: Colors.white, fontSize: 14),)
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  ///跳转输入编号页面
  void _jumpInputBikeNum() async{
    _controller.pauseContinuouslyScan();
    pushForResult(InputNumberPage(), (result) async{
      if(result != null) {
        pop(result);

      } else {
        _controller.resumeContinuouslyScan();
      }
    });
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async{
    super.didChangeAppLifecycleState(state);
    if(state == AppLifecycleState.resumed) {
      _controller.resumeContinuouslyScan();
    }

    if(state == AppLifecycleState.paused) {
      _controller.pauseContinuouslyScan();
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    _controller.dispose();
    super.dispose();
  }
}`

**Comment by arcticfox1919** [comment]
@nanguaSky 具体是什么问题？如果有报错，请提供详细报错信息，麻烦清晰的描述一下具体问题

**Comment by arcticfox1919** [comment]
The requested information has not been provided for a long time.
