### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by ariona** [arcticfox1919/flutter-scankit#29]
Hi, my IOS build is error, after searching the issue this caused by target architecture which should be arm64 and i have update it in xcode. 
<img width="836" alt="Screen Shot 2022-03-07 at 16 25 02" src="https://user-images.githubusercontent.com/752483/157003630-cb835a56-bca5-439c-9876-131a6551b3a6.png">

But i still can't build it. Below is the error log

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '~/app/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by arcticfox1919** [comment]
@ariona 
Generally Simulator is x86 architecture, not ARM64. You can only use a real machine to debug this library.

**Comment by ariona** [comment]
Aah. thats why is there any workaround to make it work in simulator?
and maybe you need to add about turning off bitcode to the readme file.
