### ISSUE TITLE
自定义View扫码没有任何反映

### ISSUE THREAD

**Issue by tnngo** [arcticfox1919/flutter-scankit#30]
我是一名后端，刚上手flutter，请教一下自定义View如何进行扫码呢？经测试，示例中的自定义的View只能识别到相册里的二维码。
flutter version: 2.10.2

**Comment by arcticfox1919** [comment]
@tnngo 
可以先阅读这两篇博客

[《Flutter 最佳扫码插件》](https://arcticfox.blog.csdn.net/article/details/116238958)

[《Flutter 最佳扫码插件——自定义视图》](https://arcticfox.blog.csdn.net/article/details/120261000)

**Comment by tnngo** [comment]
@arcticfox1919 抱歉，下午在开发服务端的代码。这是我的问题，晚上吃饭时突然想到为了适配尺寸不让其[崩溃](https://github.com/arcticfox1919/flutter-scankit/issues/27)。根据作用你的提示调整了left、top、right、bottom的值，可能因为这个原因导致了识别范围出现问题，然后删除了boundingBox问题解决。
