### ISSUE TITLE
调用 pickPhoto 报错 

### ISSUE THREAD

**Issue by fengwenl** [arcticfox1919/flutter-scankit#31]
![企业微信截图_20220314154247](https://user-images.githubusercontent.com/36912847/158126847-5809f10f-3ff7-4d2a-abee-efa277ac7300.png)
![企业微信截图_20220314154324](https://user-images.githubusercontent.com/36912847/158126925-f2ffe813-b74d-4f49-989a-41a87f2994f3.png)
![企业微信截图_20220314154428](https://user-images.githubusercontent.com/36912847/158126985-268dfc31-61af-4677-bdfa-4e336b23d221.png)

使用自定义视图组件时，调用  _controller.pickPhoto(); 选择图片完毕后是能正确返回结果，但是扫描程序还在运行没有立即停止，而且报错，当第二次继续使用_controller.pickPhoto() 时直接黑屏，或者报错
Flutter 2.8.1
Android 10 及以上

**Comment by arcticfox1919** [comment]
华为scankit的自定义UI，主要用于自定义页面UI的布局，而不是交互的流程。关于交互，请参照scankit的封装好的交互逻辑，即`startScan`接口的使用
