### ISSUE TITLE
On iOS can click what's behind camera screen

### ISSUE THREAD

**Issue by ariona** [arcticfox1919/flutter-scankit#32]
When triggering `scanKit.startScan()` method, I can still tapping whats behind the camera screen, and causing it to run the action,

Below is the screenshot when i am clicking on camera screen and tap an action to open webview.

![IMG_4797](https://user-images.githubusercontent.com/752483/159843054-2ae0f336-7304-4e59-aa95-52a03a75d49f.png)

flutter_scankit: ^1.2.3
flutter: 2.10.1

**Comment by arcticfox1919** [comment]
@ariona 
Does this problem happen when the scan page is pulled up from the webview page? What is the iOS version?

**Comment by ariona** [comment]
this happen when the action behind the scanview is webview screen, it
create the image shown above.

but for non webview it still can receive touch event and opening the screen
behind the scanview.

for now i created custom view to solve the issue.

**Comment by arcticfox1919** [comment]
@ariona 
Upgrade to version 2.0.0.
