### ISSUE TITLE
默认模式打开后，不扫码直接返回，会报NULL异常

### ISSUE THREAD

**Issue by a-jiang** [arcticfox1919/flutter-scankit#34]
type 'Null' is not a subtype of type 'String' in type cast
![image](https://user-images.githubusercontent.com/9330004/164891172-3dd806d3-4dd6-44ce-acfa-2976266770ec.png)

**Comment by a-jiang** [comment]
代码修复如下：
`  Future<void> addResultListen(ResultListener onListen) async {
    var stream = _resultChannel.receiveBroadcastStream();
    if (await stream.isEmpty == true) {
      return;
    }
    _resultSubscription =
        stream.cast<String>().listen(
            onListen, cancelOnError: false);
  }`

**Comment by a-jiang** [comment]
代码修复如下：
`  Future<void> addResultListen(ResultListener onListen) async {
    var stream = _resultChannel.receiveBroadcastStream();
    if (await stream.isEmpty == true) {
      return;
    }
    _resultSubscription =
        stream.cast<String>().listen(
            onListen, cancelOnError: false);
  }`

**Comment by arcticfox1919** [comment]
已修复 [fix issues/34 ](https://github.com/arcticfox1919/flutter-scankit/commit/fea61e6abd87f7b8a06460e0337635d50c60a790)

将在下一版本发布依赖仓库，可先使用git 依赖验证
