### ISSUE TITLE
Add in the scan result scanType and scanTypeForm

### ISSUE THREAD

**Issue by sparkmobi** [arcticfox1919/flutter-scankit#36]
Hello,

In HMS sdk there is more parameter return from result listener like scanType and ScanTypeForm

```
ScanResponse response = await HmsScanUtils.startDefaultView(request);
      setState(() {
        resultScan = response.originalValue;
        codeFormatScan = response.scanType;
        resultTypeScan = response.scanTypeForm;
      });
```

could you please add them to scankit as i need to get what is the scantype, is it barcode or qrcode or datamatrix

**Comment by arcticfox1919** [comment]
@sparkmobi 
Upgrade to version 2.0.0
