### ISSUE TITLE
Undefined symbols for architecture armv7:

### ISSUE THREAD

**Issue by xiang-tina** [arcticfox1919/flutter-scankit#37]
ld: warning: ignoring file /Users/jme/jme/dev/app/flutter/flutter_energy_app_getx/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork, file is universal (x86_64,arm64) but does not contain the armv7 architecture: /Users/jme/jme/dev/app/flutter/flutter_energy_app_getx/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_HmsBitMap", referenced from:
      objc-class-ref in FLScanKitView.o
      objc-class-ref in FlutterScankitPlugin.o
  "_OBJC_CLASS_$_HmsDefaultScanViewController", referenced from:
      objc-class-ref in FlutterScankitPlugin.o
  "_OBJC_CLASS_$_HmsCustomScanViewController", referenced from:
      objc-class-ref in FLScanKitView.o
  "_OBJC_CLASS_$_HmsScanOptions", referenced from:
      objc-class-ref in FLScanKitView.o
      objc-class-ref in FlutterScankitPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

xcode13.3.1

**Comment by arcticfox1919** [comment]
@xiang-tina 
ScanKit iOS SDK does not support armv7 and x86 architectures!!!

![](https://camo.githubusercontent.com/25b33d6a3ecfee2dd578a6cae9479918837982cbe85e06338853883292f140d5/68747470733a2f2f67697465652e636f6d2f617263746963666f78313931392f496d616765486f7374696e672f7261772f6d61737465722f696d672f323032312d30392d31372e706e67)

same as [issues13](https://github.com/arcticfox1919/flutter-scankit/issues/13)
