### ISSUE TITLE
自定义扫码打开黑屏，无法相机预览

### ISSUE THREAD

**Issue by gyh124** [arcticfox1919/flutter-scankit#42]
不是自定义扫码就没问题，我的项目是混合的，使用的是flutter boost，纯flutter项目自定义扫码也是没问题的，但是混合项目打开就是黑屏

**Comment by arcticfox1919** [comment]
@gyh124 
请提供相关的报错和日志信息

**Comment by gyh124** [comment]
> @gyh124
> 请提供相关的报错和日志信息
没走生命周期，remoteView只走了on onCreate，后续的onStart onResume

**Comment by gyh124** [comment]
> @arcticfox1919 
> 请提供相关的报错和日志信息
没走生命周期，remoteView只走了on onCreate，后续的onStart onResume没走

**Comment by arcticfox1919** [comment]
和生命周期没关系,通过logcat就能获得日志信息.另外混合项目没必要使用该插件,直接使用华为原生SDK即可

**Comment by mengjie0125** [comment]
@gyh124 最后怎么解决的
