### ISSUE TITLE
请问非自定义的原生扫码界面，扫码成功后可否不退出扫码界面？

### ISSUE THREAD

**Issue by tnngo** [arcticfox1919/flutter-scankit#44]
这个场景比较适用于入库人员入货时不间断操作。
由于我是后端开发，采用自定义界面我就实现不了比较酷炫的效果了，伤心💔。是否能加个设置使其不退出扫码界面

**Comment by 309791679** [comment]
scan_kit_widget.datr 里面有 resumeContinuouslyScan  pauseContinuouslyScan接口 通过 它使用 ScanKitController

**Comment by 309791679** [comment]
ScanKitWidget（ continuouslyScan: true, ） 就可以实现

**Comment by arcticfox1919** [comment]
@tnngo 
不能，原生扫码界面是在退出时才返回结果的，不退出不会返回识别的结果
