### ISSUE TITLE
Building for iOS Simulator, but linking in dylib built for iOS

### ISSUE THREAD

**Issue by ILittleNiZi** [arcticfox1919/flutter-scankit#51]
`    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    /Users/yangni/yo-tai-cloud_-ati_-installing_-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Reachability' from project 'Pods')
    /Users/yangni/yo-tai-cloud_-ati_-installing_-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'EasyPermissionX' from project 'Pods')
    /Users/yangni/yo-tai-cloud_-ati_-installing_-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'Toast' from project 'Pods')
    /Users/yangni/yo-tai-cloud_-ati_-installing_-app/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.5.99. (in target 'FMDB' from project 'Pods')
    Result bundle written to path:
    	/var/folders/j0/l062m7q174l5tj_jclntpyhw0000gn/T/flutter_tools.htHJ9z/flutter_ios_build_temp_dirMCpEPe/temporary_xcresult_bundle
Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/yangni/yo-tai-cloud_-ati_-installing_-app/ios/Pods/ScanKitFrameWork/scansdk-ios-tool-1.0.2.300/ScanKitFrameWork.framework/ScanKitFrameWork' for architecture arm64

Could not build the application for the simulator.
Error launching application on iPhone 13. `

请问应该怎么解决呀，我是Mac Air m1芯片

**Comment by arcticfox1919** [comment]
华为这个库不支持模拟器

**Comment by ILittleNiZi** [comment]
> 华为这个库不支持模拟器

可是我运行到真机也是这么报错

**Comment by arcticfox1919** [comment]
@ILittleNiZi 
iOS系统集成统一扫码服务SDK不支持armv7架构，需要在开发工程中去掉armv7
