### ISSUE TITLE
ios16 通知栏隐私一直显示在调用相机

### ISSUE THREAD

**Issue by mdddj** [arcticfox1919/flutter-scankit#52]
如下图,当进入扫描页面后,退出,通知栏显示APP一直调用相机

退出页面执行了dispose()函数
```dart
 @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
```

![image](https://user-images.githubusercontent.com/29020213/190093676-4a5222b7-587a-49b6-93cd-c30db1744d8f.png)

**Comment by liangyao375** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/55582967/190612994-d115d7ae-b097-4a00-9bf5-f86088a22c38.png">

**Comment by liangyao375** [comment]
这个方法被注释了

**Comment by KingTom1128** [comment]
你是怎么解决的，android也有一样的问题，一直常驻显示使用摄像头

**Comment by arcticfox1919** [comment]
@mdddj @KingTom1128 
尝试升级2.0.0版本试试
