### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException 

### ISSUE THREAD

**Issue by sparkmobi** [arcticfox1919/flutter-scankit#54]
Hi,

this error is shown to some users when they click on scan by picking image

`Application tried to present modally a view controller <UIImagePickerController: 0x12998b000> that is already being presented by <FlutterViewController: 0x129809a00>.`

**Comment by arcticfox1919** [comment]
@sparkmobi 
Try upgrading to version 2.0.0.
