### ISSUE TITLE
flutter2.2空安全

### ISSUE THREAD

**Issue by DreamlessRaw** [arcticfox1919/flutter-scankit#6]
你好，作为一个初学者，我最在使用插件时出现了不支持空安全的问题，FlutterSDK为2.2版本，请问是否有考虑升级该插件，
![image](https://user-images.githubusercontent.com/47837339/126088876-9066b30c-2740-48be-afb9-ef7f0010eba8.png)

**Comment by arcticfox1919** [comment]
已升级空安全支持，版本为 1.1.0
