### ISSUE TITLE
iOS能否也支持暂停、重启扫描功能方法

### ISSUE THREAD

**Issue by li47485** [arcticfox1919/flutter-scankit#60]
/// Android support only
  Future<void> pauseContinuouslyScan() async {
    return await _channel.invokeMethod('pauseContinuouslyScan');
  }

  /// Android support only
  Future<void> resumeContinuouslyScan() async {
    return await _channel.invokeMethod('resumeContinuouslyScan');
  }

**Comment by arcticfox1919** [comment]
华为 iOS SDK目前不支持
