### ISSUE TITLE
terminating due to uncaught exception of type zxing::Exception

### ISSUE THREAD

**Issue by sparkmobi** [arcticfox1919/flutter-scankit#63]
hello

I am getting this error also 

> thread #1, queue = 'HmsImageProcesser', stop reason = signal SIGABRT
    frame #0: 0x000000020b421578 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x20b421578 <+8>:  b.lo   0x20b421598               ; <+40>
    0x20b42157c <+12>: pacibsp 
    0x20b421580 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x20b421584 <+20>: mov    x29, sp
Target 0: (Runner) stopped.

I have fixed this crash before from the pull request by eyesoffish I think you forgot to add his code update

**Comment by arcticfox1919** [comment]
@sparkmobi Upgrade to 2.0.2.
