### ISSUE TITLE
安卓的配置minSdkVersion能否支持到minSdkVersion = 21

### ISSUE THREAD

**Issue by li47485** [arcticfox1919/flutter-scankit#64]
/Users/macintoshhd/Desktop/FlutterApp/android/app/build.gradle:                               │
│ android {                                                                                     │
│   defaultConfig {                                                                             │
│     minSdkVersion 24                                                                          │
│   }                                                                                           │
│ }

**Comment by arcticfox1919** [comment]
@li47485  Upgrade to 2.0.2.
