### ISSUE TITLE
使用 ScanKitWidget 会导致ios闪退

### ISSUE THREAD

**Issue by laoduan395** [arcticfox1919/flutter-scankit#65]
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00000001067fad68 flutter_scankit`-[FLScanKitCustomMode sendEvent:](self=0x0000000282846be0, _cmd="sendEvent:", resultDic=10 key/value pairs) at FLScanKitCustomMode.m:122:5
   119 	        @"event":@0,
   120 	        @"value":scanResult
   121 	    };
-> 122 	    self->_eventSink(dict);
    	    ^
   123 	}
   124
   125 	- (UIViewController *)topViewControler{
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by laoduan395** [comment]
具在 _controller.dispose() 的时候会不规则出现这个BUG

**Comment by arcticfox1919** [comment]
After being released, message communication cannot be carried out. There seems to be a missing null check here, and this issue will be addressed later.

**Comment by laoduan395** [comment]
> After being released, message communication cannot be carried out. There seems to be a missing null check here, and this issue will be addressed later.

等你的好消息 👍

**Comment by arcticfox1919** [comment]
Upgrade to 2.0.3
