### ISSUE TITLE
iOS Automatically manage signing

### ISSUE THREAD

**Issue by indeedshaw** [arcticfox1919/flutter-scankit#66]
目前自动管理签名要如何打开？

现在似乎没有了这个选项
FAQ中：
![image](https://github.com/arcticfox1919/flutter-scankit/assets/119829832/cf5e05c0-8411-44b5-84b1-0efb0c5055ba)
@arcticfox1919

**Comment by indeedshaw** [comment]
是否考虑使用手动集成扫码的SDK？ @arcticfox1919 @arcticfox88

**Comment by arcticfox1919** [comment]
这是Flutter 插件库，并不支持配置Embed Without Signing。
此处为搬运的华为FAQ，不适用于Flutter的内容，将在晚些时候去除

**Comment by stulang** [comment]
> 这是Flutter 插件库，并不支持配置Embed Without Signing。 此处为搬运的华为FAQ，不适用于Flutter的内容，将在晚些时候去除
 现在想要实现iOS Automatically manage signing 有解决方案吗？
