### ISSUE TITLE
flutter项目,没法跑iOS 模拟器

### ISSUE THREAD

**Issue by cheerszhou** [arcticfox1919/flutter-scankit#80]
报错log:
iMac sy_flutter % flutter run    
Launching lib/main.dart on iPhone 14 Pro in debug mode...
Running pod install...                                              6.2s
Upgrading Pods-Runner.release.xcconfig
Upgrading Pods-Runner.profile.xcconfig
Upgrading Pods-Runner.debug.xcconfig
Running Xcode build...                                                  
Xcode build done.                                           25.2s
Failed to build iOS app
Error (Xcode): Building for 'iOS-simulator', but linking in dylib (/Users/iMac/Desktop/sy_flutter/ios/Pods/ScanKitFrameWork/ScanKitFrameWork.framework/ScanKitFrameWork) built
for 'iOS'

运行环境:

[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2 23C64 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)

**Comment by arcticfox1919** [comment]
cocoapods里面包不支持模拟器
